// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xjcnlymjbuggpvdnvanq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhqY25seW1qYnVnZ3B2ZG52YW5xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1NDMyOTYsImV4cCI6MjA2NzExOTI5Nn0.K3A7AJYVaVqBPYJuc2KQcOTLFP_A2oiNsKIPblUjOJ0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});